RUN_NAME = 'SCHMOD'

KDD_DATASET_FILE = "data_samples/kddcup99/kddcup.data"
KDD_SUBSET_SIZE = 6000000

BLACKBOX = 'KMeans'  # 'KMeans' 'MiniBatchKMeans'

DATASETS = ['gaussian', 'kdd', ]  # 'gaussian', 'kdd'
KS = [50]
EPSILONS = [0.1]
DELTAS = [0.1]
MS = [50]
L_TO_K_RATIOS = [1]
SKM_ITERATIONS = [2, 3]
ROUNDS = 3
MINI_BATCH_SIZE = 1000

GAUSSIANS_DIMENSIONS = 10
GAUSSIANS_NUM_POINTS = 10_000_000
GAUSSIANS_K = 50
GAUSSIANS_ALPHA = 0.0
GAUSSIANS_STD_DEV = 0.1
