name: CI
on:
  pull_request:
  push:
jobs:
  run_demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Run Soccer spark demo
      run: sbt run
      working-directory: spark
